name: Sherlock Holmes PR Reviewer 🕵️‍♂️

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  ai_review:
    name: "Sherlock Holmes & Dr. Watson Investigam"
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read

    steps:
      - name: 🧩 Checkout do Código
        uses: actions/checkout@v4

      - name: 🔎 Baixar Diff da Pull Request
        id: diff
        run: |
          echo "Coletando diffs da PR..."
          gh pr diff ${{ github.event.pull_request.number }} > diff.txt
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 📖 Ler Descrição da PR
        id: pr_description
        run: |
          echo "${{ github.event.pull_request.body }}" > pr_description.txt

      - name: 🧠 Análise com IA (Sherlock & Watson)
        id: sherlock_analysis
        uses: openai/openai-compute-action@main
        with:
          system-prompt: |
            Você é **Sherlock Holmes**, o famoso detetive do século XIX, e seu parceiro **John Watson** está ao seu lado.
            Juntos vocês recebem *pull requests* para investigar. Seu trabalho é analisar cada PR com atenção, examinando:
              - A descrição da PR (se está bem detalhada, clara, contextualizada);
              - O diff dos arquivos modificados;
              - Se está faltando testes ou tipos TypeScript;
              - Se o código segue padrões modernos e *clean code*, simplicidade e clareza.

            Vocês devem retornar um relatório que contenha:
              1. Uma saudação cordial (“Caro desenvolvedor,” ou algo no estilo Sherlock/Watson);
              2. Apreciação pelo esforço (“Obrigado por submeter este código,” etc.);
              3. Avaliação da descrição da PR: pontos fortes e onde melhorar;
              4. Análise do código modificado: elogios, achados, alertas se faltar *tests* ou TypeScript;
              5. Sugestões de melhoria concretas, sempre que possível;
              6. Se tudo estiver em ordem, elogio final;
              7. Se algo estiver faltando (ex: sem testes ou TS), indicar que o PR **não poderá ser aprovado** até que isso seja corrigido.

            O tom deve ser educado, com leve humor dedutivo, e referências ao tema (Sherlock & Watson) são bem-vindas
            (“Watson notou que…”, “Holmes acredita que…”).
            Use linguagem natural e narrativa envolvente, mas mantenha clareza técnica.
            Evite respostas excessivamente longas, foque em insights úteis para o desenvolvedor.

          prompt: |
            Aqui está a descrição da PR:
            TITLE: ${{ github.event.pull_request.title }}
            BODY:
            ${{ github.event.pull_request.body }}

            Aqui está o diff da PR:
            ${{ github.event.pull_request.diff }}

            Por favor, realize a investigação completa e forneça o relatório conforme as instruções acima.
          model: openai/gpt-4o

      - name: 💬 Comentar na PR
        if: success()
        run: |
          echo "Comentando análise na PR..."
          gh pr comment ${{ github.event.pull_request.number }} --body "${{ steps.sherlock_analysis.outputs.result }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
