name: Sherlock Holmes PR Reviewer 🕵️‍♂️

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  ai_review:
    name: "Sherlock Holmes & Dr. Watson Investigam"
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read

    steps:
      - name: 🧩 Checkout do Código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 🔎 Coletar informações da PR
        id: pr_info
        run: |
          echo "Coletando informações da PR #${{ github.event.pull_request.number }}..."

          # Salvar título
          echo "TITLE<<EOF" >> $GITHUB_ENV
          echo "${{ github.event.pull_request.title }}" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

          # Salvar descrição
          echo "BODY<<EOF" >> $GITHUB_ENV
          echo "${{ github.event.pull_request.body }}" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 📝 Baixar Diff da Pull Request
        id: diff
        run: |
          echo "Coletando diff da PR..."
          gh pr diff ${{ github.event.pull_request.number }} > diff.txt

          # Limitar o tamanho do diff para não exceder limites da API
          if [ $(wc -c < diff.txt) -gt 50000 ]; then
            echo "DIFF<<EOF" >> $GITHUB_ENV
            head -c 50000 diff.txt >> $GITHUB_ENV
            echo -e "\n\n... (diff truncado por limite de tamanho)" >> $GITHUB_ENV
            echo "EOF" >> $GITHUB_ENV
          else
            echo "DIFF<<EOF" >> $GITHUB_ENV
            cat diff.txt >> $GITHUB_ENV
            echo "EOF" >> $GITHUB_ENV
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 🧠 Análise com IA (Sherlock & Watson)
        id: sherlock_analysis
        run: |
          echo "Enviando análise para a IA..."

          # Criar script Python para gerar o payload JSON
          cat > create_payload.py << 'PYTHON_EOF'
          import json
          import os
          import sys

          title = os.environ.get('TITLE', '')
          body = os.environ.get('BODY', '')
          diff = os.environ.get('DIFF', '')

          system_prompt = """Você é **Sherlock Holmes**, o famoso detetive do século XIX, e seu parceiro **John Watson** está ao seu lado. Juntos vocês recebem pull requests para investigar.

          Seu trabalho é analisar cada PR com atenção, examinando:
          - A descrição da PR (se está bem detalhada, clara, contextualizada);
          - O diff dos arquivos modificados;
          - Se está faltando testes ou tipos TypeScript;
          - Se o código segue padrões modernos e clean code, simplicidade e clareza.

          Vocês devem retornar um relatório que contenha:
          1. Uma saudação cordial ("Caro desenvolvedor," ou algo no estilo Sherlock/Watson);
          2. Apreciação pelo esforço ("Obrigado por submeter este código," etc.);
          3. Avaliação da descrição da PR: pontos fortes e onde melhorar;
          4. Análise do código modificado: elogios, achados, alertas se faltar tests ou TypeScript;
          5. Sugestões de melhoria concretas, sempre que possível;
          6. Se tudo estiver em ordem, elogio final;
          7. Se algo estiver faltando (ex: sem testes ou TS), indicar que o PR **não poderá ser aprovado** até que isso seja corrigido.

          O tom deve ser educado, com leve humor dedutivo, e referências ao tema (Sherlock & Watson) são bem-vindas ("Watson notou que…", "Holmes acredita que…"). Use linguagem natural e narrativa envolvente, mas mantenha clareza técnica. Evite respostas excessivamente longas, foque em insights úteis para o desenvolvedor."""

          user_prompt = f"""Aqui está a Pull Request para investigação:

          ## TÍTULO DA PR:
          {title}

          ## DESCRIÇÃO DA PR:
          {body if body else '(Sem descrição fornecida)'}

          ## DIFF DA PR:
          ```diff
          {diff}
          ```

          Por favor, realize a investigação completa e forneça o relatório conforme as instruções acima."""

          payload = {
              "model": "gpt-4o",
              "messages": [
                  {
                      "role": "system",
                      "content": system_prompt
                  },
                  {
                      "role": "user",
                      "content": user_prompt
                  }
              ],
              "temperature": 0.7,
              "max_tokens": 2000
          }

          print(json.dumps(payload, ensure_ascii=False, indent=2))
          PYTHON_EOF

          # Gerar o payload JSON
          python3 create_payload.py > payload.json

          # Fazer a chamada para a API da OpenAI
          RESPONSE=$(curl -s https://api.openai.com/v1/chat/completions \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ secrets.OPENAI_API_KEY }}" \
            -d @payload.json)

          # Salvar a resposta completa para debug
          echo "$RESPONSE" > response.json

          # Criar script Python para extrair a análise
          cat > extract_analysis.py << 'PYTHON_EOF'
          import json
          import sys

          try:
              with open('response.json', 'r') as f:
                  response = json.load(f)
              
              if 'error' in response:
                  print(f"❌ Erro da API OpenAI: {response['error'].get('message', 'Erro desconhecido')}")
                  sys.exit(1)
              
              analysis = response.get('choices', [{}])[0].get('message', {}).get('content', 'Erro ao processar análise')
              print(analysis)
          except Exception as e:
              print(f"❌ Erro ao processar resposta: {str(e)}")
              sys.exit(1)
          PYTHON_EOF

          # Extrair a análise
          ANALYSIS=$(python3 extract_analysis.py)

          # Verificar se houve erro
          if [ $? -ne 0 ]; then
            echo "Erro ao extrair análise. Resposta da API:"
            cat response.json
            exit 1
          fi

          # Salvar análise para o próximo step
          echo "ANALYSIS<<EOF" >> $GITHUB_ENV
          echo "$ANALYSIS" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

          echo "✅ Análise concluída com sucesso!"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TITLE: ${{ env.TITLE }}
          BODY: ${{ env.BODY }}
          DIFF: ${{ env.DIFF }}

      - name: 💬 Comentar na PR
        if: success()
        run: |
          echo "Publicando análise na PR..."

          # Criar comentário formatado
          cat > comment.md << 'COMMENT_EOF'
          ## 🕵️‍♂️ Investigação de Sherlock Holmes & Dr. Watson

          ${{ env.ANALYSIS }}

          ---
          *Análise automática gerada por IA • Sherlock Holmes PR Reviewer*
          COMMENT_EOF

          # Postar comentário
          gh pr comment ${{ github.event.pull_request.number }} --body-file comment.md
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: ⚠️ Tratamento de Erros
        if: failure()
        run: |
          echo "Houve um erro durante a análise. Verifique os logs acima."
          gh pr comment ${{ github.event.pull_request.number }} --body "⚠️ **Atenção**: A análise automática de Sherlock Holmes encontrou um problema técnico. Por favor, revise manualmente esta PR."
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
